version: "3"

services:
  backend:
    container_name: backend_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/home/src/miniproject
    command: npm start
